### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by MikeBergmann** [anikinmd/zed_bitbake#2] opened 2024-09-05 11:34 UTC
I'm having unusual syntax highlighting using zed 0.151.1 on Ubuntu  and bitbake extension 0.0.2

![Screenshot from 2024-09-05 13-32-33](https://github.com/user-attachments/assets/88675679-f7ae-4d70-aab0-2b1f3000b23f)

**Comment by anikinmd** [comment] 2024-09-06 08:56
@MikeBergmann, I see
Somehow, line 149 breaks the syntax highlight

**Comment by anikinmd** [comment] 2024-09-08 06:27
What happens is that bitbake and bash syntax overlap each other. I need to add a bash tree-sitter and figure out how to make it work only for bitbake functions. 
Any suggestions are appreciated.

**Comment by jdelbefoss** [comment] 2024-09-09 15:24
What about trying to detect the do_* functions as bitbake tasks?
Maybe at least the well-known ones?
https://docs.yoctoproject.org/dev/ref-manual/tasks.html

**Comment by anikinmd** [comment] 2024-09-09 17:50
That's what I thought to do. Also, We may need a tree-sitter for Python, as bitbake recipes can have Python functions and anonymous Python functions.
The problem is that config.toml allows configuring tree-sitter usage by file name/extension pattern (.bb, .bbappend). I don't see the possibility of configuring it by some text pattern inside the file.

UPD: this looks promising:
https://github.com/zed-industries/zed/blob/main/docs/src/extensions/languages.md#code-injections

**Comment by anikinmd** [comment] 2024-09-12 04:04
@MikeBergmann Fix was merged into the extensions repo.

**Comment by anikinmd** [comment] 2024-09-21 22:52
@MikeBergmann Did you try an update?

**Comment by MikeBergmann** [comment] 2024-09-23 11:05
@anikinmd Yes, thanks a lot. It's looking much better now.

**Closed as completed** 2024-09-23 11:06 UTC
